name: Flutter Build & Release

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release
        - bundle

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
          
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Get Flutter packages
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Build APK Debug
      if: github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == null
      run: |
        flutter build apk --debug --target-platform android-arm64
        flutter build apk --debug --target-platform android-arm
        flutter build apk --debug --target-platform android-x64
        
    - name: Build APK Release
      if: github.event.inputs.build_type == 'release'
      run: |
        flutter build apk --release --target-platform android-arm64
        flutter build apk --release --target-platform android-arm
        flutter build apk --release --target-platform android-x64
        
    - name: Build App Bundle
      if: github.event.inputs.build_type == 'bundle'
      run: flutter build appbundle --release
        
    - name: Upload Debug APKs
      if: github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == null
      uses: actions/upload-artifact@v4
      with:
        name: debug-apks
        path: |
          build/app/outputs/flutter-apk/app-arm64-debug.apk
          build/app/outputs/flutter-apk/app-arm-debug.apk
          build/app/outputs/flutter-apk/app-x64-debug.apk
        retention-days: 30
        
    - name: Upload Release APKs
      if: github.event.inputs.build_type == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: release-apks
        path: |
          build/app/outputs/flutter-apk/app-arm64-release.apk
          build/app/outputs/flutter-apk/app-arm-release.apk
          build/app/outputs/flutter-apk/app-x64-release.apk
        retention-days: 30
        
    - name: Upload App Bundle
      if: github.event.inputs.build_type == 'bundle'
      uses: actions/upload-artifact@v4
      with:
        name: app-bundle
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 30
        
    - name: Create Release
      if: github.event.inputs.build_type == 'release' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/app/outputs/flutter-apk/app-arm64-release.apk
          build/app/outputs/flutter-apk/app-arm-release.apk
          build/app/outputs/flutter-apk/app-x64-release.apk
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: |
          🚀 Flutter App Build v${{ github.run_number }}
          
          ## 📱 APK Files
          - **ARM64**: app-arm64-release.apk
          - **ARM**: app-arm-release.apk  
          - **x64**: app-x64-release.apk
          
          ## 🔧 Build Info
          - Flutter Version: 3.24.5
          - Build Date: ${{ github.event.head_commit.timestamp }}
          - Commit: ${{ github.sha }}
        draft: false
        prerelease: false 