name: Flutter Build & Release

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release
        - bundle

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v4
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        
    - name: Cache Flutter dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.pub-cache
          .dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          ${{ runner.os }}-flutter-
          
    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Get Flutter packages
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      
    - name: Build APK Debug
      if: github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == null
      run: |
        flutter build apk --debug --target-platform android-arm64
        flutter build apk --debug --target-platform android-arm
        
    - name: Build APK Release
      if: github.event.inputs.build_type == 'release'
      run: |
        flutter build apk --release --target-platform android-arm64
        flutter build apk --release --target-platform android-arm
        
    - name: Build App Bundle
      if: github.event.inputs.build_type == 'bundle'
      run: flutter build appbundle --release
        
    - name: Upload Debug APKs
      if: github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == null
      uses: actions/upload-artifact@v4
      with:
        name: debug-apks
        path: |
          build/app/outputs/flutter-apk/app-arm64-debug.apk
          build/app/outputs/flutter-apk/app-arm-debug.apk
        retention-days: 30
        
    - name: Upload Release APKs
      if: github.event.inputs.build_type == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: release-apks
        path: |
          build/app/outputs/flutter-apk/app-arm64-release.apk
          build/app/outputs/flutter-apk/app-arm-release.apk
        retention-days: 30
        
    - name: Upload App Bundle
      if: github.event.inputs.build_type == 'bundle'
      uses: actions/upload-artifact@v4
      with:
        name: app-bundle
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 30
        
    - name: Create Release
      if: github.event.inputs.build_type == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/app-arm64-release.apk
          build/app/outputs/flutter-apk/app-arm-release.apk
        tag_name: v${{ github.event.inputs.version || '1.0.0' }}
        name: Release v${{ github.event.inputs.version || '1.0.0' }}
        body: |
          Flutter APK Release
          
          - ARM64 APK for modern devices
          - ARM APK for older devices
          
          Download and install on your Android device.
        draft: false
        prerelease: false 